In [1]:
import numpy as np
import scipy 
import scipy.linalg 

### Задание № 2

In [3]:
# 2.1

A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
B = np.array([[4, -17, 0]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]


(3, 3)

т.к. rank A = rank С = числу неизвестных, то система определена, т. е. имеет единственное решение;

In [4]:
# 2.2

A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
B = np.array([[1, -2, 5]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]


(1, 2)

т.к. rank A < rank С, то система несовместна, решений нет.

In [5]:
A = np.array([[1, 2, 5], [3, 1, -8]])
B = np.array([[4, -4]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  2  5  4]
 [ 3  1 -8 -4]]


(2, 2)

(rank A = rank C) < числа неизвестных, система имеет бесконечное количество решений.

### Задание № 3

In [6]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
B = np.array([[3, 2, 4, 1]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]


(4, 4)

rank A = rank С = числу неизвестных, то система определена, т. е. имеет единственное решение.